// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/commerce/cart.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartListRequest) Reset() {
	*x = CartListRequest{}
	mi := &file_proto_commerce_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartListRequest) ProtoMessage() {}

func (x *CartListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commerce_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartListRequest.ProtoReflect.Descriptor instead.
func (*CartListRequest) Descriptor() ([]byte, []int) {
	return file_proto_commerce_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartListRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint64                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_proto_commerce_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commerce_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_proto_commerce_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CartItem) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CartListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartListResponse) Reset() {
	*x = CartListResponse{}
	mi := &file_proto_commerce_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartListResponse) ProtoMessage() {}

func (x *CartListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commerce_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartListResponse.ProtoReflect.Descriptor instead.
func (*CartListResponse) Descriptor() ([]byte, []int) {
	return file_proto_commerce_cart_proto_rawDescGZIP(), []int{2}
}

func (x *CartListResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_commerce_cart_proto protoreflect.FileDescriptor

const file_proto_commerce_cart_proto_rawDesc = "" +
	"\n" +
	"\x19proto/commerce/cart.proto\x12\x10commerce.cart.v1\"*\n" +
	"\x0fCartListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"=\n" +
	"\bCartItem\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x04R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"D\n" +
	"\x10CartListResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.commerce.cart.v1.CartItemR\x05items2\\\n" +
	"\vCartService\x12M\n" +
	"\x04List\x12!.commerce.cart.v1.CartListRequest\x1a\".commerce.cart.v1.CartListResponseB\x1bZ\x19seckill-mall/common/pb;pbb\x06proto3"

var (
	file_proto_commerce_cart_proto_rawDescOnce sync.Once
	file_proto_commerce_cart_proto_rawDescData []byte
)

func file_proto_commerce_cart_proto_rawDescGZIP() []byte {
	file_proto_commerce_cart_proto_rawDescOnce.Do(func() {
		file_proto_commerce_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_commerce_cart_proto_rawDesc), len(file_proto_commerce_cart_proto_rawDesc)))
	})
	return file_proto_commerce_cart_proto_rawDescData
}

var file_proto_commerce_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_commerce_cart_proto_goTypes = []any{
	(*CartListRequest)(nil),  // 0: commerce.cart.v1.CartListRequest
	(*CartItem)(nil),         // 1: commerce.cart.v1.CartItem
	(*CartListResponse)(nil), // 2: commerce.cart.v1.CartListResponse
}
var file_proto_commerce_cart_proto_depIdxs = []int32{
	1, // 0: commerce.cart.v1.CartListResponse.items:type_name -> commerce.cart.v1.CartItem
	0, // 1: commerce.cart.v1.CartService.List:input_type -> commerce.cart.v1.CartListRequest
	2, // 2: commerce.cart.v1.CartService.List:output_type -> commerce.cart.v1.CartListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_commerce_cart_proto_init() }
func file_proto_commerce_cart_proto_init() {
	if File_proto_commerce_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_commerce_cart_proto_rawDesc), len(file_proto_commerce_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_commerce_cart_proto_goTypes,
		DependencyIndexes: file_proto_commerce_cart_proto_depIdxs,
		MessageInfos:      file_proto_commerce_cart_proto_msgTypes,
	}.Build()
	File_proto_commerce_cart_proto = out.File
	file_proto_commerce_cart_proto_goTypes = nil
	file_proto_commerce_cart_proto_depIdxs = nil
}
