// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/commerce/catalog.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CatalogGetSKUSnapshotRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SkuIds          []uint64               `protobuf:"varint,1,rep,packed,name=sku_ids,json=skuIds,proto3" json:"sku_ids,omitempty"`
	IncludeInactive bool                   `protobuf:"varint,2,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CatalogGetSKUSnapshotRequest) Reset() {
	*x = CatalogGetSKUSnapshotRequest{}
	mi := &file_proto_commerce_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogGetSKUSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogGetSKUSnapshotRequest) ProtoMessage() {}

func (x *CatalogGetSKUSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commerce_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogGetSKUSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CatalogGetSKUSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_commerce_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *CatalogGetSKUSnapshotRequest) GetSkuIds() []uint64 {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

func (x *CatalogGetSKUSnapshotRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

type CatalogSKUSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint64                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SpuId         uint64                 `protobuf:"varint,2,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	SkuCode       string                 `protobuf:"bytes,3,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	SkuName       string                 `protobuf:"bytes,4,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	PriceCents    int64                  `protobuf:"varint,5,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogSKUSnapshot) Reset() {
	*x = CatalogSKUSnapshot{}
	mi := &file_proto_commerce_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogSKUSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogSKUSnapshot) ProtoMessage() {}

func (x *CatalogSKUSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commerce_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogSKUSnapshot.ProtoReflect.Descriptor instead.
func (*CatalogSKUSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_commerce_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *CatalogSKUSnapshot) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CatalogSKUSnapshot) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *CatalogSKUSnapshot) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *CatalogSKUSnapshot) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *CatalogSKUSnapshot) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *CatalogSKUSnapshot) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type CatalogGetSKUSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogSKUSnapshot  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogGetSKUSnapshotResponse) Reset() {
	*x = CatalogGetSKUSnapshotResponse{}
	mi := &file_proto_commerce_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogGetSKUSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogGetSKUSnapshotResponse) ProtoMessage() {}

func (x *CatalogGetSKUSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commerce_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogGetSKUSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CatalogGetSKUSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_commerce_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *CatalogGetSKUSnapshotResponse) GetItems() []*CatalogSKUSnapshot {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_commerce_catalog_proto protoreflect.FileDescriptor

const file_proto_commerce_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/commerce/catalog.proto\x12\x13commerce.catalog.v1\"b\n" +
	"\x1cCatalogGetSKUSnapshotRequest\x12\x17\n" +
	"\asku_ids\x18\x01 \x03(\x04R\x06skuIds\x12)\n" +
	"\x10include_inactive\x18\x02 \x01(\bR\x0fincludeInactive\"\xb1\x01\n" +
	"\x12CatalogSKUSnapshot\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\x04R\x05skuId\x12\x15\n" +
	"\x06spu_id\x18\x02 \x01(\x04R\x05spuId\x12\x19\n" +
	"\bsku_code\x18\x03 \x01(\tR\askuCode\x12\x19\n" +
	"\bsku_name\x18\x04 \x01(\tR\askuName\x12\x1f\n" +
	"\vprice_cents\x18\x05 \x01(\x03R\n" +
	"priceCents\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\"^\n" +
	"\x1dCatalogGetSKUSnapshotResponse\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.commerce.catalog.v1.CatalogSKUSnapshotR\x05items2\x89\x01\n" +
	"\x0eCatalogService\x12w\n" +
	"\x0eGetSKUSnapshot\x121.commerce.catalog.v1.CatalogGetSKUSnapshotRequest\x1a2.commerce.catalog.v1.CatalogGetSKUSnapshotResponseB\x1bZ\x19seckill-mall/common/pb;pbb\x06proto3"

var (
	file_proto_commerce_catalog_proto_rawDescOnce sync.Once
	file_proto_commerce_catalog_proto_rawDescData []byte
)

func file_proto_commerce_catalog_proto_rawDescGZIP() []byte {
	file_proto_commerce_catalog_proto_rawDescOnce.Do(func() {
		file_proto_commerce_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_commerce_catalog_proto_rawDesc), len(file_proto_commerce_catalog_proto_rawDesc)))
	})
	return file_proto_commerce_catalog_proto_rawDescData
}

var file_proto_commerce_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_commerce_catalog_proto_goTypes = []any{
	(*CatalogGetSKUSnapshotRequest)(nil),  // 0: commerce.catalog.v1.CatalogGetSKUSnapshotRequest
	(*CatalogSKUSnapshot)(nil),            // 1: commerce.catalog.v1.CatalogSKUSnapshot
	(*CatalogGetSKUSnapshotResponse)(nil), // 2: commerce.catalog.v1.CatalogGetSKUSnapshotResponse
}
var file_proto_commerce_catalog_proto_depIdxs = []int32{
	1, // 0: commerce.catalog.v1.CatalogGetSKUSnapshotResponse.items:type_name -> commerce.catalog.v1.CatalogSKUSnapshot
	0, // 1: commerce.catalog.v1.CatalogService.GetSKUSnapshot:input_type -> commerce.catalog.v1.CatalogGetSKUSnapshotRequest
	2, // 2: commerce.catalog.v1.CatalogService.GetSKUSnapshot:output_type -> commerce.catalog.v1.CatalogGetSKUSnapshotResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_commerce_catalog_proto_init() }
func file_proto_commerce_catalog_proto_init() {
	if File_proto_commerce_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_commerce_catalog_proto_rawDesc), len(file_proto_commerce_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_commerce_catalog_proto_goTypes,
		DependencyIndexes: file_proto_commerce_catalog_proto_depIdxs,
		MessageInfos:      file_proto_commerce_catalog_proto_msgTypes,
	}.Build()
	File_proto_commerce_catalog_proto = out.File
	file_proto_commerce_catalog_proto_goTypes = nil
	file_proto_commerce_catalog_proto_depIdxs = nil
}
