// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/commerce/commerce_order.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommerceOrderService_Create_FullMethodName = "/commerce.order.v1.CommerceOrderService/Create"
	CommerceOrderService_Get_FullMethodName    = "/commerce.order.v1.CommerceOrderService/Get"
)

// CommerceOrderServiceClient is the client API for CommerceOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommerceOrderServiceClient interface {
	Create(ctx context.Context, in *OrderCreateRequest, opts ...grpc.CallOption) (*OrderCreateResponse, error)
	Get(ctx context.Context, in *OrderGetRequest, opts ...grpc.CallOption) (*OrderGetResponse, error)
}

type commerceOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommerceOrderServiceClient(cc grpc.ClientConnInterface) CommerceOrderServiceClient {
	return &commerceOrderServiceClient{cc}
}

func (c *commerceOrderServiceClient) Create(ctx context.Context, in *OrderCreateRequest, opts ...grpc.CallOption) (*OrderCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderCreateResponse)
	err := c.cc.Invoke(ctx, CommerceOrderService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commerceOrderServiceClient) Get(ctx context.Context, in *OrderGetRequest, opts ...grpc.CallOption) (*OrderGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderGetResponse)
	err := c.cc.Invoke(ctx, CommerceOrderService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommerceOrderServiceServer is the server API for CommerceOrderService service.
// All implementations must embed UnimplementedCommerceOrderServiceServer
// for forward compatibility.
type CommerceOrderServiceServer interface {
	Create(context.Context, *OrderCreateRequest) (*OrderCreateResponse, error)
	Get(context.Context, *OrderGetRequest) (*OrderGetResponse, error)
	mustEmbedUnimplementedCommerceOrderServiceServer()
}

// UnimplementedCommerceOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommerceOrderServiceServer struct{}

func (UnimplementedCommerceOrderServiceServer) Create(context.Context, *OrderCreateRequest) (*OrderCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCommerceOrderServiceServer) Get(context.Context, *OrderGetRequest) (*OrderGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCommerceOrderServiceServer) mustEmbedUnimplementedCommerceOrderServiceServer() {}
func (UnimplementedCommerceOrderServiceServer) testEmbeddedByValue()                              {}

// UnsafeCommerceOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommerceOrderServiceServer will
// result in compilation errors.
type UnsafeCommerceOrderServiceServer interface {
	mustEmbedUnimplementedCommerceOrderServiceServer()
}

func RegisterCommerceOrderServiceServer(s grpc.ServiceRegistrar, srv CommerceOrderServiceServer) {
	// If the following call panics, it indicates UnimplementedCommerceOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommerceOrderService_ServiceDesc, srv)
}

func _CommerceOrderService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommerceOrderServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommerceOrderService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommerceOrderServiceServer).Create(ctx, req.(*OrderCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommerceOrderService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommerceOrderServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommerceOrderService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommerceOrderServiceServer).Get(ctx, req.(*OrderGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommerceOrderService_ServiceDesc is the grpc.ServiceDesc for CommerceOrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommerceOrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "commerce.order.v1.CommerceOrderService",
	HandlerType: (*CommerceOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CommerceOrderService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CommerceOrderService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/commerce/commerce_order.proto",
}
