// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/commerce/fulfillment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FulfillmentShipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       uint64                 `protobuf:"varint,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Carrier       string                 `protobuf:"bytes,3,opt,name=carrier,proto3" json:"carrier,omitempty"`
	TrackingNo    string                 `protobuf:"bytes,4,opt,name=tracking_no,json=trackingNo,proto3" json:"tracking_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FulfillmentShipRequest) Reset() {
	*x = FulfillmentShipRequest{}
	mi := &file_proto_commerce_fulfillment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillmentShipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillmentShipRequest) ProtoMessage() {}

func (x *FulfillmentShipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commerce_fulfillment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillmentShipRequest.ProtoReflect.Descriptor instead.
func (*FulfillmentShipRequest) Descriptor() ([]byte, []int) {
	return file_proto_commerce_fulfillment_proto_rawDescGZIP(), []int{0}
}

func (x *FulfillmentShipRequest) GetActorId() uint64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *FulfillmentShipRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *FulfillmentShipRequest) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *FulfillmentShipRequest) GetTrackingNo() string {
	if x != nil {
		return x.TrackingNo
	}
	return ""
}

type FulfillmentShipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FulfillmentShipResponse) Reset() {
	*x = FulfillmentShipResponse{}
	mi := &file_proto_commerce_fulfillment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillmentShipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillmentShipResponse) ProtoMessage() {}

func (x *FulfillmentShipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commerce_fulfillment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillmentShipResponse.ProtoReflect.Descriptor instead.
func (*FulfillmentShipResponse) Descriptor() ([]byte, []int) {
	return file_proto_commerce_fulfillment_proto_rawDescGZIP(), []int{1}
}

func (x *FulfillmentShipResponse) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *FulfillmentShipResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FulfillmentShipResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_commerce_fulfillment_proto protoreflect.FileDescriptor

const file_proto_commerce_fulfillment_proto_rawDesc = "" +
	"\n" +
	" proto/commerce/fulfillment.proto\x12\x17commerce.fulfillment.v1\"\x89\x01\n" +
	"\x16FulfillmentShipRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\x04R\aactorId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x18\n" +
	"\acarrier\x18\x03 \x01(\tR\acarrier\x12\x1f\n" +
	"\vtracking_no\x18\x04 \x01(\tR\n" +
	"trackingNo\"l\n" +
	"\x17FulfillmentShipResponse\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x7f\n" +
	"\x12FulfillmentService\x12i\n" +
	"\x04Ship\x12/.commerce.fulfillment.v1.FulfillmentShipRequest\x1a0.commerce.fulfillment.v1.FulfillmentShipResponseB\x1bZ\x19seckill-mall/common/pb;pbb\x06proto3"

var (
	file_proto_commerce_fulfillment_proto_rawDescOnce sync.Once
	file_proto_commerce_fulfillment_proto_rawDescData []byte
)

func file_proto_commerce_fulfillment_proto_rawDescGZIP() []byte {
	file_proto_commerce_fulfillment_proto_rawDescOnce.Do(func() {
		file_proto_commerce_fulfillment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_commerce_fulfillment_proto_rawDesc), len(file_proto_commerce_fulfillment_proto_rawDesc)))
	})
	return file_proto_commerce_fulfillment_proto_rawDescData
}

var file_proto_commerce_fulfillment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_commerce_fulfillment_proto_goTypes = []any{
	(*FulfillmentShipRequest)(nil),  // 0: commerce.fulfillment.v1.FulfillmentShipRequest
	(*FulfillmentShipResponse)(nil), // 1: commerce.fulfillment.v1.FulfillmentShipResponse
}
var file_proto_commerce_fulfillment_proto_depIdxs = []int32{
	0, // 0: commerce.fulfillment.v1.FulfillmentService.Ship:input_type -> commerce.fulfillment.v1.FulfillmentShipRequest
	1, // 1: commerce.fulfillment.v1.FulfillmentService.Ship:output_type -> commerce.fulfillment.v1.FulfillmentShipResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_commerce_fulfillment_proto_init() }
func file_proto_commerce_fulfillment_proto_init() {
	if File_proto_commerce_fulfillment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_commerce_fulfillment_proto_rawDesc), len(file_proto_commerce_fulfillment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_commerce_fulfillment_proto_goTypes,
		DependencyIndexes: file_proto_commerce_fulfillment_proto_depIdxs,
		MessageInfos:      file_proto_commerce_fulfillment_proto_msgTypes,
	}.Build()
	File_proto_commerce_fulfillment_proto = out.File
	file_proto_commerce_fulfillment_proto_goTypes = nil
	file_proto_commerce_fulfillment_proto_depIdxs = nil
}
