// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/commerce/identity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityAddressSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AddressId     uint64                 `protobuf:"varint,2,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityAddressSnapshotRequest) Reset() {
	*x = IdentityAddressSnapshotRequest{}
	mi := &file_proto_commerce_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityAddressSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityAddressSnapshotRequest) ProtoMessage() {}

func (x *IdentityAddressSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commerce_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityAddressSnapshotRequest.ProtoReflect.Descriptor instead.
func (*IdentityAddressSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_commerce_identity_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityAddressSnapshotRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IdentityAddressSnapshotRequest) GetAddressId() uint64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

type IdentityAddressSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressId     uint64                 `protobuf:"varint,1,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Recipient     string                 `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Province      string                 `protobuf:"bytes,5,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,7,opt,name=district,proto3" json:"district,omitempty"`
	Detail        string                 `protobuf:"bytes,8,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityAddressSnapshot) Reset() {
	*x = IdentityAddressSnapshot{}
	mi := &file_proto_commerce_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityAddressSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityAddressSnapshot) ProtoMessage() {}

func (x *IdentityAddressSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commerce_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityAddressSnapshot.ProtoReflect.Descriptor instead.
func (*IdentityAddressSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_commerce_identity_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityAddressSnapshot) GetAddressId() uint64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *IdentityAddressSnapshot) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IdentityAddressSnapshot) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *IdentityAddressSnapshot) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *IdentityAddressSnapshot) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *IdentityAddressSnapshot) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *IdentityAddressSnapshot) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *IdentityAddressSnapshot) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_proto_commerce_identity_proto protoreflect.FileDescriptor

const file_proto_commerce_identity_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/commerce/identity.proto\x12\x14commerce.identity.v1\"X\n" +
	"\x1eIdentityAddressSnapshotRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x02 \x01(\x04R\taddressId\"\xe9\x01\n" +
	"\x17IdentityAddressSnapshot\x12\x1d\n" +
	"\n" +
	"address_id\x18\x01 \x01(\x04R\taddressId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\tR\trecipient\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1a\n" +
	"\bprovince\x18\x05 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\a \x01(\tR\bdistrict\x12\x16\n" +
	"\x06detail\x18\b \x01(\tR\x06detail2\x8c\x01\n" +
	"\x0fIdentityService\x12y\n" +
	"\x12GetAddressSnapshot\x124.commerce.identity.v1.IdentityAddressSnapshotRequest\x1a-.commerce.identity.v1.IdentityAddressSnapshotB\x1bZ\x19seckill-mall/common/pb;pbb\x06proto3"

var (
	file_proto_commerce_identity_proto_rawDescOnce sync.Once
	file_proto_commerce_identity_proto_rawDescData []byte
)

func file_proto_commerce_identity_proto_rawDescGZIP() []byte {
	file_proto_commerce_identity_proto_rawDescOnce.Do(func() {
		file_proto_commerce_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_commerce_identity_proto_rawDesc), len(file_proto_commerce_identity_proto_rawDesc)))
	})
	return file_proto_commerce_identity_proto_rawDescData
}

var file_proto_commerce_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_commerce_identity_proto_goTypes = []any{
	(*IdentityAddressSnapshotRequest)(nil), // 0: commerce.identity.v1.IdentityAddressSnapshotRequest
	(*IdentityAddressSnapshot)(nil),        // 1: commerce.identity.v1.IdentityAddressSnapshot
}
var file_proto_commerce_identity_proto_depIdxs = []int32{
	0, // 0: commerce.identity.v1.IdentityService.GetAddressSnapshot:input_type -> commerce.identity.v1.IdentityAddressSnapshotRequest
	1, // 1: commerce.identity.v1.IdentityService.GetAddressSnapshot:output_type -> commerce.identity.v1.IdentityAddressSnapshot
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_commerce_identity_proto_init() }
func file_proto_commerce_identity_proto_init() {
	if File_proto_commerce_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_commerce_identity_proto_rawDesc), len(file_proto_commerce_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_commerce_identity_proto_goTypes,
		DependencyIndexes: file_proto_commerce_identity_proto_depIdxs,
		MessageInfos:      file_proto_commerce_identity_proto_msgTypes,
	}.Build()
	File_proto_commerce_identity_proto = out.File
	file_proto_commerce_identity_proto_goTypes = nil
	file_proto_commerce_identity_proto_depIdxs = nil
}
