// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/commerce/payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCreateRequest) Reset() {
	*x = PaymentCreateRequest{}
	mi := &file_proto_commerce_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreateRequest) ProtoMessage() {}

func (x *PaymentCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commerce_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreateRequest.ProtoReflect.Descriptor instead.
func (*PaymentCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_commerce_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentCreateRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PaymentCreateRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type PaymentCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	AmountCents   int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCreateResponse) Reset() {
	*x = PaymentCreateResponse{}
	mi := &file_proto_commerce_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreateResponse) ProtoMessage() {}

func (x *PaymentCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commerce_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreateResponse.ProtoReflect.Descriptor instead.
func (*PaymentCreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_commerce_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentCreateResponse) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *PaymentCreateResponse) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *PaymentCreateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_commerce_payment_proto protoreflect.FileDescriptor

const file_proto_commerce_payment_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/commerce/payment.proto\x12\x13commerce.payment.v1\"J\n" +
	"\x14PaymentCreateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"q\n" +
	"\x15PaymentCreateResponse\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2q\n" +
	"\x0ePaymentService\x12_\n" +
	"\x06Create\x12).commerce.payment.v1.PaymentCreateRequest\x1a*.commerce.payment.v1.PaymentCreateResponseB\x1bZ\x19seckill-mall/common/pb;pbb\x06proto3"

var (
	file_proto_commerce_payment_proto_rawDescOnce sync.Once
	file_proto_commerce_payment_proto_rawDescData []byte
)

func file_proto_commerce_payment_proto_rawDescGZIP() []byte {
	file_proto_commerce_payment_proto_rawDescOnce.Do(func() {
		file_proto_commerce_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_commerce_payment_proto_rawDesc), len(file_proto_commerce_payment_proto_rawDesc)))
	})
	return file_proto_commerce_payment_proto_rawDescData
}

var file_proto_commerce_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_commerce_payment_proto_goTypes = []any{
	(*PaymentCreateRequest)(nil),  // 0: commerce.payment.v1.PaymentCreateRequest
	(*PaymentCreateResponse)(nil), // 1: commerce.payment.v1.PaymentCreateResponse
}
var file_proto_commerce_payment_proto_depIdxs = []int32{
	0, // 0: commerce.payment.v1.PaymentService.Create:input_type -> commerce.payment.v1.PaymentCreateRequest
	1, // 1: commerce.payment.v1.PaymentService.Create:output_type -> commerce.payment.v1.PaymentCreateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_commerce_payment_proto_init() }
func file_proto_commerce_payment_proto_init() {
	if File_proto_commerce_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_commerce_payment_proto_rawDesc), len(file_proto_commerce_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_commerce_payment_proto_goTypes,
		DependencyIndexes: file_proto_commerce_payment_proto_depIdxs,
		MessageInfos:      file_proto_commerce_payment_proto_msgTypes,
	}.Build()
	File_proto_commerce_payment_proto = out.File
	file_proto_commerce_payment_proto_goTypes = nil
	file_proto_commerce_payment_proto_depIdxs = nil
}
