global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'catalog-service'
    static_configs:
      - targets: ['catalog-service:9102']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:9103']

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rabbitmq:15692']
