syntax = "proto3";

package commerce.order.v1;

option go_package = "seckill-mall/common/pb;pb";

message OrderItemInput {
  uint64 sku_id = 1;
  int32 quantity = 2;
}

message OrderCreateRequest {
  string idempotency_key = 1;
  uint64 user_id = 2;
  uint64 address_id = 3;
  string order_type = 4;
  repeated OrderItemInput items = 5;
}

message OrderCreateResponse {
  string order_id = 1;
  string status = 2;
  int64 total_amount_cents = 3;
  bool reused = 4;
  string message = 5;
}

message OrderGetRequest {
  uint64 user_id = 1;
  string order_id = 2;
}

message OrderGetResponse {
  string order_id = 1;
  uint64 user_id = 2;
  string order_type = 3;
  string status = 4;
  int64 total_amount_cents = 5;
}

service CommerceOrderService {
  rpc Create(OrderCreateRequest) returns (OrderCreateResponse);
  rpc Get(OrderGetRequest) returns (OrderGetResponse);
}
