server:
  name: "order-service"
  port: "51005"
  metrics_port: ""
  mode: "debug"

mysql:
  dsn: "" # 推荐通过环境变量 SECKILL_MYSQL_DSN 注入

mq:
  url: "" # 推荐通过环境变量 SECKILL_MQ_URL 注入

redis:
  addr: "localhost:6379"
  password: "" # 推荐通过环境变量 SECKILL_REDIS_PASSWORD 注入
  db: 1

etcd:
  addr: "127.0.0.1:2379"

seckill:
  purchase_limit: 5 #配置限购件数

jwt:
  expire: "5s"

order:
  service_name: "order-service"
  address: "127.0.0.1:51005"
  mysql_dsn: ""

catalog:
  service_name: "catalog-service"
  address: "127.0.0.1:51002"

identity:
  service_name: "identity-service"
  address: "127.0.0.1:51001"

inventory:
  service_name: "inventory-service"
  address: "127.0.0.1:51003"
